plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "https://raw.githubusercontent.com/yarnpkg/berry/%40yarnpkg/cli/3.0.0/packages/plugin-workspace-tools/bin/%40yarnpkg/plugin-workspace-tools.js"

yarnPath: .yarn/releases/yarn-sources.cjs

enableGlobalCache: true

packageExtensions:
  hardhat@*:
    dependencies:
      "@types/mocha": "^9.0.0"
    peerDependencies:
      "eth-gas-reporter": "*"
  hardhat-typechain@*:
    dependencies:
      fs-extra: "^7.0.0"
      ts-generator: "^0.1.1"
    peerDependencies:
      ethers: "*"
      typescript: "*"
  typechain@*:
    peerDependencies:
      ethers: "^5.0.0"
      typescript: "*"
      "@typechain/ethers-v5": "*"
  "@typechain/ethers-v5@*":
    dependencies:
      lodash: "^4.17.15"
      ts-generator: "^0.1.1"
  rlp@^2.2.6:
    dependencies:
      "@types/bn.js": "^4.11.3"
  "@ethereumjs/vm@^5.5.2":
    dependencies:
      rlp: "^2.0.0"
  ethereum-waffle@*:
    peerDependencies:
      typescript: "*"
  "@ethereum-waffle/chai@^3.4.0":
    dependencies:
      "@types/sinon-chai": "^3.2.5"
  "@ethereum-waffle/compiler@*":
    peerDependencies:
      typescript: "*"
  eth-block-tracker@*:
    dependencies:
      "@babel/core": ""
  hardhat-gas-reporter@*:
    peerDependencies:
      typescript: "*"
  eth-gas-reporter@*:
    dependencies:
      "@codechecks/client": ""
    peerDependencies:
      typescript: "*"
  "@codechecks/client@*":
    peerDependencies:
      typescript: "*"
  "@resolver-engine/imports-fs@*":
    dependencies:
      "@resolver-engine/core": "^0.3.3"
  mocha@*:
    peerDependencies:
      "eth-gas-reporter": "*"
